version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: |
          docker build -t docker-react -f Dockerfile.dev .
          docker run -e CI=true docker-react npm run test