version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t docker-react -f Dockerfile.dev .
          docker run -e CI=true docker-react npm run test